name = "image-toolbox-api"
main = "index.js"
compatibility_date = "2026-03-27"
workers_dev = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "image-toolbox-users"
database_id = "4babd4a4-f671-4cef-ba09-41c8fbf130c1"

# Environment variables
[vars]
GOOGLE_CLIENT_ID = "300047558352-79f5fjc6vtdoljont9ukuvdme2g4e65h.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Ov23liIWfTJGMpqRArKK"
GITHUB_CLIENT_SECRET = "02274a5074582b097bfcb3df37e19b4eaab36805"
